# Generated by Django 6.0.3 on 2026-03-19 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveField(
            model_name='class',
            name='day',
        ),
        migrations.AddField(
            model_name='class',
            name='minutes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('friday', models.ManyToManyField(blank=True, related_name='friday_groups', to='myapp.class')),
                ('monday', models.ManyToManyField(blank=True, related_name='monday_groups', to='myapp.class')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgroups', to='myapp.group')),
                ('thursday', models.ManyToManyField(blank=True, related_name='thursday_groups', to='myapp.class')),
                ('tuesday', models.ManyToManyField(blank=True, related_name='tuesday_groups', to='myapp.class')),
                ('wednesday', models.ManyToManyField(blank=True, related_name='wednesday_groups', to='myapp.class')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
