# Generated by Django 6.0.3 on 2026-03-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_class_options_remove_class_day_class_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.CharField(choices=[('math', 'Math'), ('history', 'History'), ('science', 'Science'), ('english', 'English'), ('language', 'Language'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
